/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Agents } from "./Agents";
import { AgentsCountArgs } from "./AgentsCountArgs";
import { AgentsFindManyArgs } from "./AgentsFindManyArgs";
import { AgentsFindUniqueArgs } from "./AgentsFindUniqueArgs";
import { CreateAgentsArgs } from "./CreateAgentsArgs";
import { UpdateAgentsArgs } from "./UpdateAgentsArgs";
import { DeleteAgentsArgs } from "./DeleteAgentsArgs";
import { User } from "../../user/base/User";
import { AgentsService } from "../agents.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Agents)
export class AgentsResolverBase {
  constructor(
    protected readonly service: AgentsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Agents",
    action: "read",
    possession: "any",
  })
  async _agentsItemsMeta(
    @graphql.Args() args: AgentsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Agents])
  @nestAccessControl.UseRoles({
    resource: "Agents",
    action: "read",
    possession: "any",
  })
  async agentsItems(
    @graphql.Args() args: AgentsFindManyArgs
  ): Promise<Agents[]> {
    return this.service.agentsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Agents, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Agents",
    action: "read",
    possession: "own",
  })
  async agents(
    @graphql.Args() args: AgentsFindUniqueArgs
  ): Promise<Agents | null> {
    const result = await this.service.agents(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Agents)
  @nestAccessControl.UseRoles({
    resource: "Agents",
    action: "create",
    possession: "any",
  })
  async createAgents(@graphql.Args() args: CreateAgentsArgs): Promise<Agents> {
    return await this.service.createAgents({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Agents)
  @nestAccessControl.UseRoles({
    resource: "Agents",
    action: "update",
    possession: "any",
  })
  async updateAgents(
    @graphql.Args() args: UpdateAgentsArgs
  ): Promise<Agents | null> {
    try {
      return await this.service.updateAgents({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Agents)
  @nestAccessControl.UseRoles({
    resource: "Agents",
    action: "delete",
    possession: "any",
  })
  async deleteAgents(
    @graphql.Args() args: DeleteAgentsArgs
  ): Promise<Agents | null> {
    try {
      return await this.service.deleteAgents(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Agents): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
